source 'https://rubygems.org'
ruby ' 2.7.6'

gem 'appium_lib'
gem 'appom'
gem 'byebug'
gem 'capybara'
gem 'capybara-screenshot'
#gem 'chunky_png', '1.3.7'
gem 'chunky_png'
#gem 'cucumber', '3.1.2'
gem 'cucumber'
gem 'cuke_sniffer'
gem 'dotenv'
#gem 'faker', '>= 2.15.1'
#gem 'foreman', '~> 0.87.2'
#gem 'imatcher', '0.1.5'
gem 'new_data_magic', '~> 1.2'
gem 'os'
gem 'parallel_tests'
gem 'pry'
gem 'pry-byebug'
gem 'rake'
gem 'report_builder'
gem 'require_all'
#gem 'rspec', '~> 3.5'
gem 'rspec'
#gem 'rspec-expectations', '3.5.0'
#gem 'rubocop', '0.59.2', require: false
gem 'show_me_the_cookies'
#gem 'site_prism', '2.16'
gem 'site_prism'
gem 'site_prism-table'
gem 'spreadsheet'
gem 'syntax'
gem 'touch_action'
gem 'selenium-cucumber'
gem 'selenium-webdriver'